/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f8f9fa",
        "surface-variant": "#e1e3e4",
        "on-tertiary-fixed-variant": "#7d2d00",
        "error-container": "#ffdad6",
        "on-background": "#191c1d",
        "on-surface": "#191c1d",
        "on-secondary-fixed-variant": "#31447b",
        "primary": "#004ac6",
        "surface-container-low": "#f3f4f5",
        "surface-tint": "#0053db",
        "surface-container-high": "#e7e8e9",
        "secondary-fixed-dim": "#b4c5ff",
        "primary-container": "#2563eb",
        "surface-dim": "#d9dadb",
        "tertiary-container": "#bc4800",
        "error": "#ba1a1a",
        "tertiary": "#943700",
        "secondary-container": "#acbfff",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f0f1f2",
        "surface": "#f8f9fa",
        "on-tertiary-fixed": "#360f00",
        "primary-fixed-dim": "#b4c5ff",
        "surface-container": "#edeeef",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffede6",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#ffb596",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "on-primary-fixed": "#00174b",
        "on-secondary-container": "#394c84",
        "secondary": "#495c95",
        "outline-variant": "#c3c6d7",
        "on-error": "#ffffff",
        "secondary-fixed": "#dbe1ff",
        "on-primary-fixed-variant": "#003ea8",
        "on-surface-variant": "#434655",
        "background": "#f8f9fa",
        "on-secondary-fixed": "#00174b",
        "outline": "#737686",
        "tertiary-fixed": "#ffdbcd",
        "on-primary-container": "#eeefff",
        "inverse-primary": "#b4c5ff",
        "inverse-surface": "#2e3132",
        "primary-fixed": "#dbe1ff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
